---
title: "Treat peatlands 2015"
author: "K Todd-Brown (ktoddbrown@gmail.com)"
date: "8/3/2017"
output:
  pdf_document:
    fig_caption: yes
    toc: yes
  html_document: default
---

```{r setup}
library(SoilDataR) #library(devtools); install_github("ktoddbrown/soilDataR")
library(ggplot2) #make pretty plots
library(plyr) #data management
library(dplyr)
library(knitr)
library(lubridate)
library(tidyr)

#mapping librarys to help with global/regional plots
library(ggmap)
library(maps)
library(mapdata)
library(fiftystater)
```

```{r loadData, cache=TRUE}
Treat <- SoilDataR::processData_Treat2015(dir='../repoData/Treat_2015/')
#ISCN3 <- SoilDataR::processData_ISCN3(dir='../repoData/ISCN_3/')
```

#Observation time
```{r obsTime}
location.df <- unique(Treat$field[, c('lat', 'long', 'observation_date', 
                                       'state', 'country')])
location.df$year <- location.df$observation_date

location.df$obsDate <- ymd(paste(location.df$year, 1, 1, sep="-"))
location.df <- location.df[order(location.df$lat, location.df$long, location.df$obsDate),]
location.df$yrCut <- cut(location.df$year, c(1950, 1960, 1970, 1980, 1990, 2000, 2013), dig.lab=4)
#location.df$yrCut <- location.df$year
location.df$latCut <- cut(location.df$lat, seq(-90, 90, by=0.05))
location.df$longCut <- cut(location.df$long, seq(-180, 180, by=0.05))

timeSpaceCounts <- location.df %>%
  mutate(inUSA = country %in% 'United States') %>%
  group_by(yrCut, latCut, longCut, inUSA) %>%
  tally
```
```{r plotTime}
ggplot(location.df, aes(x=obsDate)) + geom_histogram()

mapWorld <- borders("world", colour="gray80", fill="gray80") # create a layer of borders
#ggplot() + mapWorld
ggplot(location.df) +
  mapWorld + 
  #geom_hex(aes(x=long, y=lat), bins=200) + 
  geom_point(aes(x=long, y=lat), alpha=0.1, color='red') +
  scale_fill_gradient(trans='log10') +
  theme_bw() +
  theme(text=element_text(size=18)) +
  labs(x='', y='') +
  ylim(45, 90) + 
  coord_map(projection='azequidistant') +
  facet_wrap(~yrCut)

#ggplot(location.df, aes(x=long, y=lat)) + geom_point(alpha=0.1)

ggplot(timeSpaceCounts, aes(x=n)) + geom_histogram() + 
  scale_x_log10() + scale_y_log10()+ facet_wrap(~inUSA, scales='free') +
  labs(title='Close space-time sites by USA status')
```

# Site locations
## Lat-lon map
```{r mapSites}

mapWorld <- borders("world", colour="gray80", fill="gray80") # create a layer of borders
#ggplot() + mapWorld
ggplot(unique(Treat$field[, c('lat', 'long')])) +
  mapWorld + 
  geom_hex(aes(x=long, y=lat), bins=200) + 
  scale_fill_gradient(trans='log10') +
  theme_bw() +
  theme(text=element_text(size=18)) +
  labs(x='', y='')
```

# Measruements distribution

```{r measurementHist}
ggplot(subset(Treat$sample, measurementID %in% c('14c_age', 'n_tot', 'c_tot', 'loi')), aes(x=value)) +
  geom_histogram() +
  facet_wrap(measurementID~unit, scales='free')

ggplot(subset(Treat$sample, !measurementID %in% c('14c_age', 'n_tot')), aes(x=value)) +
  geom_histogram() +
  scale_x_log10() +
  facet_wrap(measurementID~unit, scales='free')
```

# Comparison with ISCN3

```{r loadISCN3, cache=TRUE}
ISCN <- processData_ISCN3(dir='../repoData/ISCN_3/')
```

```{r trimISCN}
#only keep things that overlap
ISCN$measurement <- subset(ISCN$measurement, as.character(type) %in% c(as.character(Treat$measurement$type), '14c'))

ISCN$sample <- subset(ISCN$sample, as.character(measurementID) %in% as.character(ISCN$measurement$measurementID))

ISCN$field <- subset(ISCN$field, as.character(fieldID) %in% as.character(ISCN$sample$fieldID))

ISCN$field <- ISCN$field %>%
  separate(observation_date, c('monthStr', 'dayStr', 'yearStr'), 
           remove=FALSE, fill='left') %>%
  mutate(year=ifelse(as.numeric(yearStr) < 20, as.numeric(yearStr) + 2000,
                     ifelse(as.numeric(yearStr) < 100, as.numeric(yearStr) + 1900,
                            as.numeric(yearStr))),
         month=as.numeric(monthStr), day=as.numeric(dayStr),
         OLD_observation_date=as.character(observation_date)) %>%
 select(-contains('Str'))

ISCN$field$observation_date <- decimal_date(ymd(paste(ISCN$field$year, 
                                             ISCN$field$month, ISCN$field$day, sep="-")))

ISCN$sample <- merge(ISCN$sample, ISCN$measurement, all.x=TRUE)
Treat$sample <- merge(Treat$sample, Treat$measurement, all.x=TRUE)
```

```{r}
ggplot(subset(Treat$sample, type %in% c('14c_age', 'n_tot', 'c_tot', 'loi')), 
       aes(x=value, y=..density..)) +
  geom_histogram(data=subset(ISCN$sample, grepl('(14c)|(n_tot)|(c_tot)|(loi)', type)), aes(x=value, y=..density..), fill='grey') + 
  geom_histogram(fill='red', alpha=0.5) +
  facet_wrap(~type, scales='free')

ggplot(subset(Treat$sample, !type %in% c('14c_age', 'n_tot', 'c_tot', 'loi')), 
       aes(x=value, y=..density..)) +
  geom_histogram(data=subset(ISCN$sample, !grepl('(14c)|(n_tot)|(c_tot)|(loi)', type)), aes(x=value, y=..density..), fill='grey') + 
  geom_histogram(fill='red', alpha=0.5) +
  scale_x_log10() + 
  facet_wrap(unit~type, scales='free')
```

#High latitude points
```{r subsetSpaceISCN}

ISCN$field$TreatLat <- ISCN$field$lat > floor(min(Treat$field$lat))

ggplot(Treat$field, aes(x=long, y=lat)) +
  geom_point(data=subset(ISCN$field, TreatLat), aes(x=long, y=lat), alpha=0.1) + 
  geom_point(color='red', alpha=0.1)

ggplot(subset(Treat$sample, type %in% c('14c_age', 'n_tot', 'c_tot', 'loi')), 
       aes(x=value, y=..density..)) +
  geom_histogram(data=subset(ISCN$sample, 
                             as.character(fieldID) %in% 
                               as.character(subset(ISCN$field, TreatLat)$fieldID) &
                               grepl('(14c)|(n_tot)|(c_tot)|(loi)', type)), 
                 aes(x=value, y=..density..), fill='grey') + 
  geom_histogram(fill='red', alpha=0.5) +
  facet_wrap(~type, scales='free')

ggplot(subset(Treat$sample, !type %in% c('14c_age', 'n_tot', 'c_tot', 'loi')), 
       aes(x=value, y=..density..)) +
  geom_histogram(data=subset(ISCN$sample,
                              as.character(fieldID) %in% 
                               as.character(subset(ISCN$field, TreatLat)$fieldID) &
                               !grepl('(14c)|(n_tot)|(c_tot)|(loi)', type)), aes(x=value, y=..density..), fill='grey') + 
  geom_histogram(fill='red', alpha=0.5) +
  scale_x_log10() + 
  facet_wrap(unit~type, scales='free')

```


There might be some overlaping sites. The intersecting field ID's are [`r print(intersect(ISCN$field$fieldID, Treat$field$fieldID))`].

#Neighbor sites distribution
```{r pullGrids}

ISCN$field$studyID <- ISCN$study$studyID
Treat$field$studyID <- as.factor(Treat$study$studyID)
allField <- rbind.fill(ISCN$field, Treat$field)
allField <- subset(allField, is.finite(lat+long))
allField$binLat <- cut(allField$lat, seq(-90, 90, by=2))
allField$binLong <- cut(allField$long, seq(-180, 180, by=2))
allField$binDate <- floor(allField$observation_date)

#pull the 'grids' with Treat in it
allField <- ddply(allField, c('binLat', 'binLong'), function(xx){
  if(any(xx$studyID %in% c('Treat_peat_2015'))){
    return(xx)
  }else{
    return()
  }
})

ggplot(allField, aes(x=long, y=lat, color=studyID)) + 
  geom_point(alpha=0.5) +
  facet_wrap(~studyID) +
  labs(title='plot everything')

ggplot(subset(Treat$sample, type %in% c('14c_age', 'n_tot', 'c_tot', 'loi')), 
       aes(x=value, y=..density..)) +
  geom_histogram(data=subset(ISCN$sample, 
                             fieldID %in% allField$fieldID &
                               grepl('(14c)|(n_tot)|(c_tot)|(loi)', type)), 
                 aes(x=value, y=..density..), fill='grey') + 
  geom_histogram(fill='red', alpha=0.5) +
  facet_wrap(~type, scales='free')

ggplot(subset(Treat$sample, !type %in% c('14c_age', 'n_tot', 'c_tot', 'loi')), 
       aes(x=value, y=..density..)) +
  geom_histogram(data=subset(ISCN$sample,  
                             fieldID %in% allField$fieldID &
                               !grepl('(14c)|(n_tot)|(c_tot)|(loi)', type)), 
                 aes(x=value, y=..density..), fill='grey') + 
  geom_histogram(fill='red', alpha=0.5) +
  scale_x_log10() + 
  facet_wrap(unit~type, scales='free')

```

#Duplicate ISCN points?
```{r duplicateCheck}

ISCN$field$studyID <- ISCN$study$studyID
Treat$field$studyID <- as.factor(Treat$study$studyID)
allField <- rbind.fill(ISCN$field, Treat$field)
allField <- subset(allField, is.finite(lat+long))
allField$binLat <- cut(allField$lat, seq(-90, 90, by=0.1))
allField$binLong <- cut(allField$long, seq(-180, 180, by=0.1))
allField$binDate <- floor(allField$observation_date)

#pull the 'grids' with Treat in it
allField <- ddply(allField, c('binLat', 'binLong'), function(xx){
  if(any(xx$studyID %in% c('Treat_peat_2015'))){
    return(xx)
  }else{
    return()
  }
})

countSpaceTime <- allField %>%
  group_by(binLat, binLong, binDate, studyID) %>%
  tally %>%
  spread(studyID, n)

overlap <- subset(countSpaceTime, is.finite(`ISCN 1-1 (2015-12-10)` + Treat_peat_2015)) %>%
  gather(studyID, count, `ISCN 1-1 (2015-12-10)`:Treat_peat_2015)
print(overlap)

busyField <- merge(overlap, allField, by=c('binLat', 'binLong', 'binDate', 'studyID'))

ggplot(busyField, aes(x=long, y=lat, color=studyID)) + geom_point()
```

