---
title: "ISCN viz"
author: "K Todd-Brown (ktoddbrown@gmail.com)"
date: "4/26/2017"
output:
  pdf_document: 
    fig_caption: yes
    toc: yes
  html_document: default
---

```{r setup}
library(ggplot2)
library(ggmap)
library(maps)
library(mapdata)
library(plyr)
library(fiftystater)
```

```{r loadData}
source('./processData_ISCN3.R')

ISCN3 <- processData_ISCN3(dir='.')
```


#Map of sites
```{r mapSites}

mapWorld <- borders("world", colour="gray80", fill="gray80") # create a layer of borders
#ggplot() + mapWorld
ggplot(unique(ISCN3$field[, c('lat', 'long')])) +
  mapWorld + 
  geom_hex(aes(x=long, y=lat), bins=200) + 
  scale_fill_gradient(trans='log10')
```
```{r mapSiteByArea}
noLatLon <- unique(subset(ISCN3$field, is.na(lat+long))$fieldID)

stateCounts <- ddply(subset(ISCN3$fieldNotes, measurement == 'state' & fieldID %in% noLatLon), c('value'), summarize, count=length(unique(fieldID)))
names(stateCounts)[1] <- 'state'
stateCounts$state <- tolower(stateCounts$state)
stateCounts <- subset(stateCounts, state %in% fifty_states$id)


ggplot(stateCounts, aes(map_id = state)) +
  geom_map(aes(fill=count), map=fifty_states) +
  expand_limits(x = fifty_states$long, y = fifty_states$lat) +
  coord_map() +
  scale_x_continuous(breaks = NULL) + 
  scale_y_continuous(breaks = NULL) +
  scale_fill_gradient(trans='log10') +
  labs(x = "", y = "") +
  theme(legend.position = "bottom", 
        panel.background = element_blank())

countryCounts <- ddply(subset(ISCN3$fieldNotes, measurement == 'country' & fieldID %in% noLatLon), c('value'), summarize, count=length(unique(fieldID)))
names(countryCounts)[1] <- 'region'
countryCounts$region <- as.character(countryCounts$region)
countryCounts$region[grepl('United States', countryCounts$region)] <- 'USA'

map.world <- map_data(map="world")

missingCountries <- data.frame(region=setdiff(map.world$region, countryCounts$value), count=NA)
countryCounts <- rbind(countryCounts, missingCountries)
#map.world <- merge(map.world, countryCounts, all=TRUE)
ggplot(countryCounts, aes(map_id = region)) +
  geom_map(aes(fill=count), map=map.world) +
  expand_limits(x = map.world$long, y = map.world$lat) +
  coord_cartesian(xlim=c(-180,180), ylim=c(-90,90)) +
  scale_x_continuous(breaks = NULL) + 
  scale_y_continuous(breaks = NULL) +
  scale_fill_gradient(trans='log10') +
  labs(x = "", y = "") +
  theme(legend.position = "bottom", 
        panel.background = element_blank())



```

`r nrow(subset(subset(ISCN3$fieldNotes, measurement == 'country' & fieldID %in% noLatLon),
            value=='Unknown'))` ites with no known country.

##Total country counts
```{r totCountryCount}
countryCounts <- ddply(subset(ISCN3$fieldNotes, measurement == 'country'), c('value'), summarize, count=length(unique(fieldID)))
names(countryCounts)[1] <- 'region'
countryCounts$region <- as.character(countryCounts$region)
countryCounts$region[grepl('United States', countryCounts$region)] <- 'USA'


map.world <- map_data(map="world")

missingCountries <- data.frame(region=setdiff(map.world$region, countryCounts$region), count=NA)
setdiff(countryCounts$region, map.world$region)
countryCounts <- rbind(countryCounts, missingCountries)
#map.world <- merge(map.world, countryCounts, all=TRUE)
ggplot(countryCounts, aes(map_id = region)) +
  geom_map(aes(fill=count), map=map.world) +
  expand_limits(x = map.world$long, y = map.world$lat) +
  coord_cartesian(xlim=c(-180,180), ylim=c(-90,90)) +
  scale_x_continuous(breaks = NULL) + 
  scale_y_continuous(breaks = NULL) +
  scale_fill_gradient(trans='log10') +
  labs(x = "", y = "") +
  theme(legend.position = "bottom", 
        panel.background = element_blank())
```

#Histograms of measurements
```{r types}
unique(ISCN3$measurement$type)
```

```{r BD}
ggplot(merge(subset(ISCN3$sample, grepl('^bd_', measurementID) & value > 0 & value < 10),
             ISCN3$measurement)) +
  geom_histogram(aes(x=value, y=..density..)) + 
  scale_x_log10() + 
  facet_wrap(type~unit)

summary(subset(ISCN3$sample, grepl('^bd_', measurementID) & (value < 0 | value > 10)))
```

```{r C_OC_LOI}
ggplot(merge(subset(ISCN3$sample, grepl('^(c_|oc|loi)', measurementID) & value > 0),
             ISCN3$measurement)) +
  geom_histogram(aes(x=value, y=..density..)) + 
  scale_x_log10() + 
  facet_wrap(type~unit)

summary(subset(ISCN3$sample, grepl('^(c_|oc|loi)', measurementID) & (value < 0)))
```

```{r N}
ggplot(merge(subset(ISCN3$sample, grepl('^n_', measurementID) & value > 0),
             ISCN3$measurement)) +
  geom_histogram(aes(x=value, y=..density..)) + 
  scale_x_log10() + 
  facet_wrap(type~unit)
```

```{r pH}
ggplot(merge(subset(ISCN3$sample, grepl('^ph_', measurementID) & value > 1.5),
             ISCN3$measurement)) +
  geom_histogram(aes(x=value, y=..density..)) + 
  #scale_x_log10() + 
  facet_wrap(type~unit)

summary(subset(ISCN3$sample, grepl('^ph_', measurementID) & (value <= 1.5)))
```

```{r CaCO3}

ggplot(merge(subset(ISCN3$sample, grepl('^caco3', measurementID) & value > 0),
             ISCN3$measurement)) +
  geom_histogram(aes(x=value, y=..density..)) + 
  scale_x_log10() + 
  facet_wrap(type~unit)

summary(subset(ISCN3$sample, grepl('^caco3', measurementID) & (value <= 0)))

```

```{r Texture}

ggplot(merge(subset(ISCN3$sample, grepl('tot_psa', measurementID) & value >= 0),
             ISCN3$measurement)) +
  geom_histogram(aes(x=value, y=..density..)) + 
  #scale_x_log10() + 
  facet_wrap(type~unit)

summary(subset(ISCN3$sample, grepl('tot_psa', measurementID) & (value < 0)))

```

```{r cat_wpg}

ggplot(merge(subset(ISCN3$sample, grepl('(cat_exch)', measurementID)& (value > 0)),
             ISCN3$measurement)) +
  geom_histogram(aes(x=value, y=..density..)) + 
  scale_x_log10() + 
  facet_wrap(type~unit)

summary(subset(ISCN3$sample, grepl('(cat_exch)', measurementID) & (value <= 0)))

subset(ISCN3$measurement,grepl('(cat_exch)', measurementID))
```

```{r wpg}
ggplot(merge(subset(ISCN3$sample, grepl('wpg2', measurementID) & value > 0),
             ISCN3$measurement)) +
  geom_histogram(aes(x=value, y=..density..)) + 
  scale_x_log10() + 
  facet_wrap(type~unit)

#summary(summary(subset(ISCN3$sample, grepl('wpg2', measurementID) & (value <= 0))))
```

```{r metals_percent}
ggplot(merge(subset(ISCN3$sample, 
                    grepl('^(al|fe|mn|ca|k|mg|na|p)_', measurementID) &
                      !grepl('ext', measurementID)),
             ISCN3$measurement)) +
  geom_histogram(aes(x=value, y=..density..)) + 
  scale_x_log10() + 
  facet_wrap(type~unit, scales='free')

summary(subset(ISCN3$sample, grepl('^(al|fe|mn|ca|k|mg|na|p)_', measurementID) &
                      !grepl('ext', measurementID) & (value > 100)))
```
```{r metals_ext}
ggplot(merge(subset(ISCN3$sample, grepl('ext', measurementID) & value > 0),
             ISCN3$measurement)) +
  geom_histogram(aes(x=value, y=..density..)) + 
  scale_x_log10() + 
  facet_wrap(type~unit, scales='free')

summary(subset(ISCN3$sample, grepl('ext', measurementID) & (value <= 0)))
```

```{r base_cec}
#base_sum     cec_sum      ecec         bs           bs_sum 
ggplot(merge(subset(ISCN3$sample, grepl('(base_sum|cec_sum|ecec)_', measurementID) & 
                      value > 0),
             ISCN3$measurement)) +
  geom_histogram(aes(x=value, y=..density..)) + 
  scale_x_log10() + 
  facet_wrap(type~unit, scales='free')

summary(subset(ISCN3$sample, grepl('(base_sum|cec_sum|ecec)_', measurementID) & (value <= 0)))
```

```{r bs}
#bs           bs_sum 
ggplot(merge(subset(ISCN3$sample, grepl('^bs_', measurementID)),
             ISCN3$measurement)) +
  geom_histogram(aes(x=value, y=..density..)) + 
  #scale_x_log10() + 
  facet_wrap(type~unit, scales='free')

#summary(subset(ISCN3$sample, grepl('^bs_', measurementID)))
```

```{r isotope}
#15n          13c          14c
ggplot(merge(subset(ISCN3$sample, grepl('^1[345]', measurementID)),
             ISCN3$measurement)) +
  geom_histogram(aes(x=value, y=..density..)) + 
  #scale_x_log10() + 
  facet_wrap(~type, scales='free')

summary(subset(ISCN3$sample, grepl('^1[345]', measurementID)))
```